### ISSUE TITLE
Invalid NMEA message that halts the execution of a py script

### ISSUE THREAD

**Issue by doncqueurs** [M0r13n/pyais#18]
While receiving data from AISHUB, I got the following error message when I ran a script to create a separate json file for every minute. It seems to point to an invalid NMEA message. This error kills the script. 

Unfortunately this happens every few minutes. It would be great if it just continues and drops the invalid nmea message. 

Error message:

```
Traceback (most recent call last):
  File "/home/rstudio/AISHUB_stream2json.py", line 23, in <module>
    for msg in TCPStream(host, port):
  File "/home/rstudio/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/pyais/stream.py", line 37, in _assemble_messages
    msg: NMEAMessage = NMEAMessage(line)
  File "/home/rstudio/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/pyais/messages.py", line 43, in __init__
    raise InvalidNMEAMessageException("A NMEA message needs to have exactly 7 comma separated entries.")
pyais.exceptions.InvalidNMEAMessageException: A NMEA message needs to have exactly 7 comma separated entries.
```

Code I used to run:

```
from pyais import TCPStream
from datetime import datetime
import json
import os
# import shutil

# AISHUB server details
host = "data.aishub.net"
port = 4214 

start = datetime.now()
# now = datetime.now()

# new_file.close()
dt_string = start.strftime("%Y%m%d_%H%M%S")
filename_parts = ["./1_stream/", "nmea_", dt_string, ".json"]
filename = "".join(filename_parts)
filename_parts_destination = ["./1_stream_completed/", "nmea_", dt_string, ".json"]
filename_destination = "".join(filename_parts_destination)

new_file=open(filename,mode="w",encoding="utf-8")

for msg in TCPStream(host, port):
  print(msg)
  # print("---")
  json_data = msg.decode().to_json()
  print("---")
  json_data = json_data.replace(' ', '') 
  json_data = json_data.replace('\n', '') 
  if (datetime.now() - start).total_seconds() > 60:
    new_file.close()
    os.rename(filename, filename_destination)
    start = datetime.now()
    dt_string = start.strftime("%Y%m%d_%H%M%S")
    filename_parts = ["./1_stream/", "nmea_", dt_string, ".json"]
    filename = "".join(filename_parts)
    filename_parts_destination = ["./1_stream_completed/", "nmea_", dt_string, ".json"]
    filename_destination = "".join(filename_parts_destination)
    new_file=open(filename,mode="w",encoding="utf-8")
  json2file = "".join([json_data,"\n"])
  print("---")
  new_file.write(json2file)
  print("---")

```

**Comment by M0r13n** [comment]
This happens if a message has fewer than 7 comma separated parts. I guess that some other message or log message is sent by AISHUB. I added a heuristic check, that make sure to only parse lines that seem to be valid NMEA messages. By doing so, it is now also possible to parse textfiles that contain messages and comments.

https://github.com/M0r13n/pyais/pull/19

**Comment by M0r13n** [comment]
@doncqueurs Can you try the current version and check if it works for you?

```bash
git clone https://github.com/M0r13n/pyais.git && cd pyais
pip install .
```

**Comment by M0r13n** [comment]
@doncqueurs Could also provide a sample of the messages causing problems? Then I could try to fix em.

**Comment by doncqueurs** [comment]
That is a bit the challenge, I haven't been able to capture the message and confirm it breaks.

I will try the new github code.

**Comment by M0r13n** [comment]
I added even more type checks and made the stream interface more gentle. It just skips invalid messages or messages that is does not understand by default. So your issue should be resolved. If you are still experiencing any hickups, feel free to reopen this issue., :-)
