### ISSUE TITLE
ValueError: invalid literal for int() with base 16: b''

### ISSUE THREAD

**Issue by AllNamesWereTakenIsNotAvailable** [M0r13n/pyais#58]
Maybe this is not as intended?

I am parsing a file of all sorts of bad data and decoding it; I handle the exceptions; however this seems like a bad way to handle a missing checksum?

!AIVDM,1,1,,A,100u3FP04r28t0<WcshcQI<H0H79,0

`Traceback (most recent call last):
  File "pyais_test.py", line 14, in <module>
    decoded = pyais.decode(i)
  File "c:\Python38\lib\site-packages\pyais\decode.py", line 34, in decode
    nmea = _assemble_messages(*parts)
  File "c:\Python38\lib\site-packages\pyais\decode.py", line 13, in _assemble_messages
    nmea = NMEAMessage(msg)
  File "c:\Python38\lib\site-packages\pyais\messages.py", line 201, in __init__
    self.checksum = int(checksum[2:], 16)
ValueError: invalid literal for int() with base 16: b''`

All the best

**Comment by M0r13n** [comment]
@AllNamesWereTakenIsNotAvailable Yes, you are right. Will be fixed with #60 and will be available in the next release.
